export const groupInfo = {
  name: "Applied AI Research Group",
  shortName: "AARG",
  department: "Department of Computer Science and Engineering",
  university: "East West University",
  address: "A/2, Jahurul Islam Avenue, Jahurul Islam City, Aftabnagar, Dhaka-1212, Bangladesh",
  email: "cse@ewubd.edu",
  website: "https://fse.ewubd.edu/computer-science-engineering",
  description:
    "We are a research group at East West University focused on applied artificial intelligence, computer vision, natural language processing, brain-computer interfaces, IoT, and knowledge graphs. Our work spans foundational research and real-world applications with societal impact.",
  researchThemes: [
    "Applied AI & Machine Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Brain-Computer Interfaces",
    "Internet of Things",
    "Knowledge Graphs & Semantic Web",
    "Graph Neural Networks",
    "Precision Agriculture AI",
  ],
};

export type FacultyRole = "Professor" | "Associate Professor";

export const faculty = [
  {
    slug: "dshr",
    name: "Dr. Shamim H Ripon",
    role: "Professor" as FacultyRole,
    email: "dshr@ewubd.edu",
    office: "Room No# 647",
    phone: "Ext: 262",
    photo: "https://fse.ewubd.edu/storage/app/uploads/public/6a3/d68/29c/6a3d6829c9668646940456.jpeg",
    profileUrl: "https://fse.ewubd.edu/computer-science-engineering/faculty-view/dshr",
    bio: "Professor Ripon is a senior faculty member with a PhD from the University of Southampton, UK, and post-doctoral experience at the Universities of Glasgow and York. His research spans software engineering, NLP, computer vision, bioinformatics, and data analytics.",
    education: [
      "PhD, Computer Science — University of Southampton, UK",
      "MSc, Computer Science — National University of Singapore",
      "BSc, Computer Science and Engineering — Khulna University",
    ],
    interests: ["Software Engineering", "NLP", "Computer Vision", "Data Analytics", "Bioinformatics", "Formal Verification"],
    achievements: "Multiple best paper awards; Elsevier outstanding peer review recognition; Fellow of Bangladesh Computer Society",
  },
  {
    slug: "wasif",
    name: "Dr. Ahmed Wasif Reza",
    role: "Professor" as FacultyRole,
    email: "wasif@ewubd.edu",
    office: "Room No# 646",
    phone: "Ext: 394",
    photo: "https://fse.ewubd.edu/storage/app/uploads/public/605/33f/fe5/60533ffe585f0525662684.jpg",
    profileUrl: "https://fse.ewubd.edu/computer-science-engineering/faculty-view/wasif",
    bio: "Dr. Reza is a Professor and Dean of the Faculty of Sciences and Engineering at EWU, with a PhD from the University of Malaya. He has authored 400+ research papers with 4,200+ citations (h-index: 31) and holds the Chartered Engineer (CEng) credential from the Engineering Council (UK).",
    education: [
      "PhD — University of Malaya, Malaysia",
      "M.Eng.Sc. — Multimedia University, Malaysia",
      "BSc (Hons), Computer Science and Engineering — Khulna University, Bangladesh",
    ],
    interests: ["Artificial Intelligence", "Machine Learning", "Deep Learning", "Brain-Computer Interfaces", "IoT", "Biomedical Image Processing", "Robotics", "Wireless Communications"],
    achievements: "400+ papers, 4,200+ citations, h-index 31; Top 3% Scientist in CS (AD Scientific Index 2024–2025); Chartered Engineer (CEng)",
  },
  {
    slug: "raihan-islam",
    name: "Dr. Raihan Ul Islam",
    role: "Associate Professor" as FacultyRole,
    email: "raihan.islam@ewubd.edu",
    office: "Room No. 256",
    phone: "Ext: 411",
    photo: "https://fse.ewubd.edu/storage/app/uploads/public/654/b5d/f47/654b5df47ef14304470505.jpg",
    profileUrl: "https://fse.ewubd.edu/computer-science-engineering/faculty-view/raihan.islam",
    bio: "Dr. Islam is an Associate Professor with a PhD from Luleå University of Technology, Sweden, and post-doctoral experience at Luleå and Ericsson AB. His research focuses on expert systems, IoT, smart city applications, and cloud and edge computing.",
    education: [
      "PhD, Pervasive Mobile Computing — Luleå University of Technology, Sweden",
      "MSc, Computer Science and Engineering — Luleå University of Technology, Sweden",
      "BSc, Computer Science and Engineering — Khulna University, Bangladesh",
    ],
    interests: ["Expert Systems", "Internet of Things", "Smart City", "Cloud & Edge Computing", "Artificial Intelligence", "Machine Learning"],
    achievements: "60+ publications in IEEE and Springer; Best paper award at IEEE INFOCOM 2017; Researcher at Ericsson AB, Sweden",
  },
  {
    slug: "rifat-rashid",
    name: "Dr. Mohammad Rifat Ahmmad Rashid",
    role: "Associate Professor" as FacultyRole,
    email: "rifat.rashid@ewubd.edu",
    office: "Room No. 646",
    phone: "",
    photo: "https://fse.ewubd.edu/storage/app/uploads/public/64b/517/679/64b5176796ce4173333910.jpg",
    profileUrl: "https://fse.ewubd.edu/computer-science-engineering/faculty-view/rifat.rashid",
    bio: "Dr. Rashid is an Associate Professor with a PhD from the Polytechnic University of Turin, Italy. His research spans computer vision, NLP, large language models, semantic web, and blockchain. He leads AVL research in applied CV and graph-enhanced AI systems.",
    education: [
      "PhD, Computer and Control Engineering — Polytechnic University of Turin, Italy",
      "MSc, Computer Engineering — University of Pavia, Italy",
      "BEng, Computer Science and Engineering — Khulna University, Bangladesh",
    ],
    interests: ["Computer Vision", "NLP & LLMs", "Knowledge Graphs", "Semantic Web", "Blockchain", "Brain-Computer Interfaces", "Precision Agriculture AI"],
    achievements: "72+ peer-reviewed publications in Elsevier, IEEE, Nature, IOS Press; 4 EWU CRT-funded research projects",
  },
];

export const researchAssistants = [
  {
    slug: "ra-1",
    name: "Research Assistant",
    role: "Graduate Research Assistant",
    status: "open",
    note: "Position to be announced",
  },
  {
    slug: "ra-2",
    name: "Research Assistant",
    role: "Graduate Research Assistant",
    status: "open",
    note: "Position to be announced",
  },
  {
    slug: "ra-3",
    name: "Research Assistant",
    role: "Undergraduate Research Assistant",
    status: "open",
    note: "Position to be announced",
  },
];

export const profile = {
  name: "Mohammad Rifat Ahmmad Rashid",
  shortName: "Rifat Rashid",
  title: "Associate Professor",
  department: "Department of Computer Science and Engineering",
  university: "East West University",
  location: "Dhaka 1212, Bangladesh",
  email: "rifat.rashid@ewubd.edu",
  github: "https://github.com/rifat963",
  scholar: "https://scholar.google.com/citations?user=fXu1UdgAAAAJ&hl=en",
  linkedin: "https://www.linkedin.com/in/mohammad-rifat-rashid-73982a5b/",
  website: "https://rifat963.github.io",
  office: "Room #646, Department of CSE, EWU",
  phone: "Ext: 446",
  interests: [
    "Applied AI & Machine Learning",
    "Computer Vision",
    "Knowledge Graphs & Semantic Web",
    "Brain-Computer Interfaces",
    "Graph Neural Networks",
    "IoT & Smart Systems",
    "Precision Agriculture AI",
  ],
  stats: {
    journals: 42,
    conferences: 24,
    bookChapters: 6,
    fundedProjects: 4,
  },
};

export type CourseColor = "teal" | "amber" | "purple";

export const courses = [
  {
    code: "CSE445",
    title: "Computer Vision",
    level: "Undergraduate",
    credits: 4,
    lectures: 24,
    modules: 10,
    color: "teal" as CourseColor,
    icon: "👁️",
    desc: "A comprehensive course covering feature detection, camera geometry, object detection, tracking, and modern deep learning approaches including Vision Transformers and NeRF.",
    repoUrl: "https://github.com/rifat963/cse445-cv-dashboard",
    dashboardUrl: "https://cse445-cv-dashboard.vercel.app",
    topics: ["Feature Detection", "Camera Geometry", "Object Detection", "Optical Flow", "Object Tracking", "Vision Transformers"],
  },
  {
    code: "CSE438",
    title: "Digital Image Processing",
    level: "Undergraduate",
    credits: 4,
    lectures: 26,
    modules: 6,
    color: "amber" as CourseColor,
    icon: "🖼️",
    desc: "Foundational course covering digital image representation, enhancement, spatial/frequency domain filtering, image restoration, and segmentation with morphological operations.",
    repoUrl: "https://github.com/rifat963/cse438-dip-dashboard",
    dashboardUrl: "https://cse438-dip-dashboard.vercel.app",
    topics: ["Image Enhancement", "Frequency Domain", "Spatial Filtering", "Wavelets", "Segmentation", "Morphology"],
  },
  {
    code: "AIML505",
    title: "Statistics for Data Science",
    level: "Graduate",
    credits: 3,
    lectures: 12,
    modules: 12,
    color: "purple" as CourseColor,
    icon: "📊",
    desc: "Graduate-level statistics covering probability theory, inference, regression, Bayesian methods, non-parametric tests, time series analysis, and graph neural networks.",
    repoUrl: "https://github.com/rifat963/aiml505-course-dashboard",
    dashboardUrl: "https://aiml505-course-dashboard.vercel.app",
    topics: ["Probability Theory", "Statistical Inference", "Regression", "Bayesian Statistics", "Time Series", "Graph Neural Networks"],
  },
] as const;

export const otherCourses = [
  { code: "CSE475", title: "Machine Learning", level: "Undergraduate" },
  { code: "CSE366", title: "Artificial Intelligence", level: "Undergraduate" },
  { code: "CSE303", title: "Statistics for Data Science", level: "Undergraduate" },
  { code: "CSE521", title: "Advanced Topics in AI", level: "Graduate" },
];

export type ProjectColor = "teal" | "amber" | "purple" | "navy";

export const projects = [
  {
    title: "Brain Computer Interface System to Control Wheelchair",
    shortTitle: "BCI Wheelchair Control System",
    role: "PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-RG-17(14)/2025(5)",
    year: 2025,
    status: "active" as const,
    tags: ["BCI", "EEG", "Motor Control", "Embedded Systems", "Deep Learning"],
    color: "teal" as ProjectColor,
    desc: "Developing a non-invasive brain-computer interface system using EEG signals to enable motor-impaired individuals to control a wheelchair through neural intent classification.",
  },
  {
    title: "BCI-Based Emotion Detection with Graph Neural Networks",
    shortTitle: "BCI Emotion Detection with GNNs",
    role: "Co-PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-2025",
    year: 2025,
    status: "active" as const,
    tags: ["BCI", "GNN", "Emotion Recognition", "EEG", "Graph Learning"],
    color: "purple" as ProjectColor,
    desc: "Applying graph neural networks to EEG-based emotion recognition, leveraging topological brain connectivity patterns for more accurate affective computing.",
  },
  {
    title: "Structured Retrieval-Augmented Generation with Knowledge Graph Databases",
    shortTitle: "Graph-Enhanced RAG",
    role: "Co-PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-2025",
    year: 2025,
    status: "active" as const,
    tags: ["RAG", "Knowledge Graphs", "LLMs", "NLP", "Graph Databases"],
    color: "navy" as ProjectColor,
    desc: "Enhancing retrieval-augmented generation pipelines with structured knowledge graph databases to improve factual accuracy and reasoning in large language model outputs.",
  },
];

export const repositories = [
  {
    name: "cse445-cv-dashboard",
    url: "https://github.com/rifat963/cse445-cv-dashboard",
    language: "TypeScript",
    desc: "Interactive course dashboard for Computer Vision (CSE445) with lecture browser, module grid, and assessment tracking.",
  },
  {
    name: "cse438-dip-dashboard",
    url: "https://github.com/rifat963/cse438-dip-dashboard",
    language: "TypeScript",
    desc: "Course dashboard for Digital Image Processing (CSE438) featuring lab manuals, segmentation series, and SSL tutorials.",
  },
  {
    name: "aiml505-course-dashboard",
    url: "https://github.com/rifat963/aiml505-course-dashboard",
    language: "TypeScript",
    desc: "Graduate-level Statistics for Data Science (AIML505) dashboard with topic progression and mini-project tracking.",
  },
  {
    name: "rifat963.github.io",
    url: "https://github.com/rifat963/rifat963.github.io",
    language: "HTML/CSS",
    desc: "Personal academic website featuring publications, research projects, teaching portfolio, and student supervision records.",
  },
];

export const recentPublications = [
  {
    title: "BDFlower: Growth stage flower image dataset for precision agriculture and floriculture",
    journal: "Data in Brief, Elsevier",
    year: 2026,
    url: "https://www.sciencedirect.com/science/article/pii/S2352340926002982",
    type: "journal" as const,
  },
  {
    title: "Temperature-Optimized Self-Supervised Contrastive Learning Enables Data-Efficient and Explainable Fabric Defect Detection",
    journal: "IEEE Access, IEEE",
    year: 2026,
    url: "https://ieeexplore.ieee.org/abstract/document/11457882",
    type: "journal" as const,
  },
  {
    title: "Real-Time Sunflower Detection Using Semi-Supervised and Self-Supervised Deep Learning for Precision Agriculture",
    journal: "Smart Agricultural Technology, Elsevier",
    year: 2025,
    url: "https://www.sciencedirect.com/science/article/pii/S2772375525009153",
    type: "journal" as const,
  },
  {
    title: "Attention guided convolutional neural network with explainable AI for papaya leaf disease detection in edge and drone agricultural systems",
    journal: "Scientific Reports, Nature Publishing Group",
    year: 2025,
    url: "https://www.nature.com/articles/s41598-025-25374-w",
    type: "journal" as const,
  },
  {
    title: "BERT-KAN: Enhancing bilingual sentiment analysis in Bangladeshi E-commerce through fine-tuned large language models",
    journal: "Natural Language Processing Journal, Elsevier",
    year: 2025,
    url: "https://www.sciencedirect.com/science/article/pii/S2949719125000664",
    type: "journal" as const,
  },
  {
    title: "A smartphone-based multi-criteria vegetable object detection dataset from Bangladesh",
    journal: "Data in Brief, Elsevier",
    year: 2025,
    url: "https://www.sciencedirect.com/science/article/pii/S2352340925010029",
    type: "journal" as const,
  },
];

export const allPublications = {
  journals: [
    { title: "BDFlower: Growth stage flower image dataset for precision agriculture and floriculture", journal: "Data in Brief, Elsevier", year: 2026, url: "https://www.sciencedirect.com/science/article/pii/S2352340926002982" },
    { title: "Temperature-Optimized Self-Supervised Contrastive Learning Enables Data-Efficient and Explainable Fabric Defect Detection", journal: "IEEE Access, IEEE", year: 2026, url: "https://ieeexplore.ieee.org/abstract/document/11457882" },
    { title: "Real-Time Sunflower Detection Using Semi-Supervised and Self-Supervised Deep Learning for Precision Agriculture", journal: "Smart Agricultural Technology, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2772375525009153" },
    { title: "Attention guided convolutional neural network with explainable AI for papaya leaf disease detection in edge and drone agricultural systems", journal: "Scientific Reports, Nature Publishing Group", year: 2025, url: "https://www.nature.com/articles/s41598-025-25374-w" },
    { title: "A smartphone-based multi-criteria vegetable object detection dataset from Bangladesh", journal: "Data in Brief, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2352340925010029" },
    { title: "A comprehensive coin dataset highlighting the numismatic heritage of Bangladesh", journal: "Data in Brief, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2352340925009333" },
    { title: "BERT-KAN: Enhancing bilingual sentiment analysis in Bangladeshi E-commerce through fine-tuned large language models", journal: "Natural Language Processing Journal, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2949719125000664" },
    { title: "Real-Time Monitoring of Oyster Mushroom Cultivation Using CCTV and Attention-Enhanced ShuffleNet-Based Explainable AI Techniques", journal: "Smart Agricultural Technology, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2772375525008020" },
    { title: "Smartphone image dataset for turmeric plant leaf disease from Bangladesh spice fields", journal: "Data in Brief, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2352340925009059" },
    { title: "Assessing the quality of DBpedia, LinkedGeoData, and Wikidata", journal: "Journal of Web Semantics, Elsevier", year: 2023, url: "https://doi.org/10.1016/j.websem.2023.100797" },
    { title: "Quality Assessment of Knowledge Graphs: A Systematic Literature Review", journal: "Semantic Web Journal, IOS Press", year: 2022, url: "#" },
    { title: "Anomaly Detection in Industrial IoT using Deep Neural Networks", journal: "IEEE Access, IEEE", year: 2021, url: "#" },
    { title: "Knowledge Base Population and Linked Data Quality Assessment", journal: "ACM Computing Surveys", year: 2020, url: "#" },
  ],
  conferences: [
    { title: "BCI-Based Motor Imagery Classification using Graph Attention Networks", journal: "IEEE ICCIT 2024", year: 2024, url: "#" },
    { title: "Precision Agriculture in Bangladesh: Challenges and Computer Vision Approaches", journal: "IEEE RAAICON 2024", year: 2024, url: "#" },
    { title: "Structured RAG with Property Graphs for Open-Domain Question Answering", journal: "ACM SAC 2024", year: 2024, url: "#" },
    { title: "Semi-Supervised Object Detection for Agricultural Applications in Low-Data Regimes", journal: "IEEE COMPAS 2023", year: 2023, url: "#" },
    { title: "IoT-Based Smart Agriculture Monitoring System with Edge AI", journal: "Springer ICDIIS 2022", year: 2022, url: "#" },
  ],
  bookChapters: [
    { title: "Knowledge Graph Quality Assessment: Dimensions, Metrics, and Methods", journal: "Chapman & Hall / CRC Press", year: 2023, url: "#" },
    { title: "Graph Neural Networks for Brain-Computer Interfaces", journal: "Chapman & Hall / CRC Press", year: 2024, url: "#" },
    { title: "Deep Learning for Precision Agriculture: A Practical Guide", journal: "IOS Press", year: 2024, url: "#" },
    { title: "Self-Supervised Learning in Computer Vision Applications", journal: "Chapman & Hall / CRC Press", year: 2023, url: "#" },
    { title: "IoT Security and Privacy: Blockchain Approaches", journal: "IOS Press", year: 2022, url: "#" },
    { title: "Retrieval-Augmented Generation Systems with Knowledge Graphs for Enterprise AI", journal: "Chapman & Hall / CRC Press", year: 2025, url: "#" },
  ],
};

export const researchAreas = [
  "Applied AI",
  "Computer Vision",
  "Knowledge Graphs",
  "Brain-Computer Interfaces",
  "Graph Neural Networks",
  "IoT & Smart Systems",
  "Blockchain Applications",
  "RAG & LLM Systems",
  "Sustainable AI",
  "Precision Agriculture AI",
];

export const tutorialSeries = [
  {
    slug: "ml-fundamentals",
    title: "Machine Learning Fundamentals",
    color: "teal" as CourseColor,
    icon: "🧠",
    level: "Beginner",
    episodeCount: 10,
    desc: "A ground-up introduction to machine learning — covering the math, algorithms, and Python implementations. For students who know basic programming but are new to ML.",
    topics: ["Linear Regression", "Decision Trees", "SVMs", "K-Means Clustering", "Neural Network Intro", "Model Evaluation", "Cross-Validation", "Feature Engineering", "Ensemble Methods", "Dimensionality Reduction"],
    comingSoon: true,
  },
  {
    slug: "deep-learning",
    title: "Deep Learning from Scratch",
    color: "purple" as CourseColor,
    icon: "🕸️",
    level: "Intermediate",
    episodeCount: 12,
    desc: "From backpropagation fundamentals through modern architectures. Each episode builds on the last, implementing key concepts in PyTorch with clear mathematical explanations.",
    topics: ["Backpropagation", "CNNs", "Batch Normalization", "Residual Networks", "Attention Mechanism", "Transformers", "Transfer Learning", "Training Tricks", "Regularization", "Model Deployment"],
    comingSoon: true,
  },
  {
    slug: "computer-vision",
    title: "Computer Vision Practicals",
    color: "amber" as CourseColor,
    icon: "👁️",
    level: "Intermediate",
    episodeCount: 10,
    desc: "Hands-on computer vision from classical feature detection through modern detection networks. Emphasizes practical implementation with real-world Bangladeshi datasets.",
    topics: ["Feature Detection", "Object Detection", "Image Segmentation", "Optical Flow", "Stereo Vision", "Self-supervised CV", "Model Deployment", "Edge AI", "NeRF Basics", "Vision Transformers"],
    comingSoon: true,
  },
];
