export const profile = {
  name: "Mohammad Rifat Ahmmad Rashid",
  shortName: "Rifat Rashid",
  title: "Associate Professor",
  department: "Department of Computer Science and Engineering",
  university: "East West University",
  location: "Dhaka 1212, Bangladesh",
  email: "rifat.rashid@ewubd.edu",
  github: "https://github.com/rifat963",
  scholar: "https://scholar.google.com/citations?user=fXu1UdgAAAAJ&hl=en",
  linkedin: "https://www.linkedin.com/in/mohammad-rifat-rashid-73982a5b/",
  website: "https://rifat963.github.io",
  office: "Room #646, Department of CSE, EWU",
  interests: [
    "Applied AI & Machine Learning",
    "Computer Vision",
    "Knowledge Graphs & Semantic Web",
    "Brain-Computer Interfaces",
    "Graph Neural Networks",
    "IoT & Smart Systems",
    "Precision Agriculture AI",
  ],
  stats: {
    journals: 42,
    conferences: 24,
    bookChapters: 6,
    fundedProjects: 4,
  },
};

export type CourseColor = "teal" | "amber" | "purple";

export const courses = [
  {
    code: "CSE445",
    title: "Computer Vision",
    level: "Undergraduate",
    credits: 4,
    lectures: 24,
    modules: 10,
    color: "teal" as CourseColor,
    icon: "👁️",
    desc: "A comprehensive course covering feature detection, camera geometry, object detection, tracking, and modern deep learning approaches including Vision Transformers and NeRF.",
    repoUrl: "https://github.com/rifat963/cse445-cv-dashboard",
    dashboardUrl: "https://cse445-cv-dashboard.vercel.app",
    topics: ["Feature Detection", "Camera Geometry", "Object Detection", "Optical Flow", "Object Tracking", "Vision Transformers"],
  },
  {
    code: "CSE438",
    title: "Digital Image Processing",
    level: "Undergraduate",
    credits: 4,
    lectures: 26,
    modules: 6,
    color: "amber" as CourseColor,
    icon: "🖼️",
    desc: "Foundational course covering digital image representation, enhancement, spatial/frequency domain filtering, image restoration, and segmentation with morphological operations.",
    repoUrl: "https://github.com/rifat963/cse438-dip-dashboard",
    dashboardUrl: "https://cse438-dip-dashboard.vercel.app",
    topics: ["Image Enhancement", "Frequency Domain", "Spatial Filtering", "Wavelets", "Segmentation", "Morphology"],
  },
  {
    code: "AIML505",
    title: "Statistics for Data Science",
    level: "Graduate",
    credits: 3,
    lectures: 12,
    modules: 12,
    color: "purple" as CourseColor,
    icon: "📊",
    desc: "Graduate-level statistics covering probability theory, inference, regression, Bayesian methods, non-parametric tests, time series analysis, and graph neural networks.",
    repoUrl: "https://github.com/rifat963/aiml505-course-dashboard",
    dashboardUrl: "https://aiml505-course-dashboard.vercel.app",
    topics: ["Probability Theory", "Statistical Inference", "Regression", "Bayesian Statistics", "Time Series", "Graph Neural Networks"],
  },
] as const;

export const otherCourses = [
  { code: "CSE475", title: "Machine Learning", level: "Undergraduate" },
  { code: "CSE366", title: "Artificial Intelligence", level: "Undergraduate" },
  { code: "CSE303", title: "Statistics for Data Science", level: "Undergraduate" },
  { code: "CSE521", title: "Advanced Topics in AI", level: "Graduate" },
];

export type ProjectColor = "teal" | "amber" | "purple" | "navy";

export const projects = [
  {
    title: "Brain Computer Interface System to Control Wheelchair",
    shortTitle: "BCI Wheelchair Control System",
    role: "PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-RG-17(14)/2025(5)",
    year: 2025,
    status: "active" as const,
    tags: ["BCI", "EEG", "Motor Control", "Embedded Systems", "Deep Learning"],
    color: "teal" as ProjectColor,
    desc: "Developing a non-invasive brain-computer interface system using EEG signals to enable motor-impaired individuals to control a wheelchair through neural intent classification.",
  },
  {
    title: "BCI-Based Emotion Detection with Graph Neural Networks",
    shortTitle: "BCI Emotion Detection with GNNs",
    role: "Co-PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-2025",
    year: 2025,
    status: "active" as const,
    tags: ["BCI", "GNN", "Emotion Recognition", "EEG", "Graph Learning"],
    color: "purple" as ProjectColor,
    desc: "Applying graph neural networks to EEG-based emotion recognition, leveraging topological brain connectivity patterns for more accurate affective computing.",
  },
  {
    title: "Structured Retrieval-Augmented Generation with Knowledge Graph Databases",
    shortTitle: "Graph-Enhanced RAG",
    role: "Co-PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-2025",
    year: 2025,
    status: "active" as const,
    tags: ["RAG", "Knowledge Graphs", "LLMs", "NLP", "Graph Databases"],
    color: "navy" as ProjectColor,
    desc: "Enhancing retrieval-augmented generation pipelines with structured knowledge graph databases to improve factual accuracy and reasoning in large language model outputs.",
  },
  {
    title: "Applied Computer Vision for Precision Agriculture in Bangladesh",
    shortTitle: "AgriVision Bangladesh",
    role: "Co-PI" as const,
    funder: "EWU CRT",
    ref: "EWUCRT-2025",
    year: 2025,
    status: "active" as const,
    tags: ["Computer Vision", "Precision Agriculture", "Deep Learning", "Drone Imaging", "Bangladesh"],
    color: "amber" as ProjectColor,
    desc: "Developing computer vision solutions for crop disease detection, yield prediction, and growth stage monitoring tailored to Bangladesh's agricultural landscape.",
  },
];

export const repositories = [
  {
    name: "cse445-cv-dashboard",
    url: "https://github.com/rifat963/cse445-cv-dashboard",
    language: "TypeScript",
    desc: "Interactive course dashboard for Computer Vision (CSE445) with lecture browser, module grid, and assessment tracking.",
  },
  {
    name: "cse438-dip-dashboard",
    url: "https://github.com/rifat963/cse438-dip-dashboard",
    language: "TypeScript",
    desc: "Course dashboard for Digital Image Processing (CSE438) featuring lab manuals, segmentation series, and SSL tutorials.",
  },
  {
    name: "aiml505-course-dashboard",
    url: "https://github.com/rifat963/aiml505-course-dashboard",
    language: "TypeScript",
    desc: "Graduate-level Statistics for Data Science (AIML505) dashboard with topic progression and mini-project tracking.",
  },
  {
    name: "rifat963.github.io",
    url: "https://github.com/rifat963/rifat963.github.io",
    language: "HTML/CSS",
    desc: "Personal academic website featuring publications, research projects, teaching portfolio, and student supervision records.",
  },
];

export const recentPublications = [
  {
    title: "BDFlower: Growth stage flower image dataset for precision agriculture and floriculture",
    journal: "Data in Brief, Elsevier",
    year: 2026,
    url: "https://www.sciencedirect.com/science/article/pii/S2352340926002982",
    type: "journal" as const,
  },
  {
    title: "Temperature-Optimized Self-Supervised Contrastive Learning Enables Data-Efficient and Explainable Fabric Defect Detection",
    journal: "IEEE Access, IEEE",
    year: 2026,
    url: "https://ieeexplore.ieee.org/abstract/document/11457882",
    type: "journal" as const,
  },
  {
    title: "Real-Time Sunflower Detection Using Semi-Supervised and Self-Supervised Deep Learning for Precision Agriculture",
    journal: "Smart Agricultural Technology, Elsevier",
    year: 2025,
    url: "https://www.sciencedirect.com/science/article/pii/S2772375525009153",
    type: "journal" as const,
  },
  {
    title: "Attention guided convolutional neural network with explainable AI for papaya leaf disease detection in edge and drone agricultural systems",
    journal: "Scientific Reports, Nature Publishing Group",
    year: 2025,
    url: "https://www.nature.com/articles/s41598-025-25374-w",
    type: "journal" as const,
  },
  {
    title: "BERT-KAN: Enhancing bilingual sentiment analysis in Bangladeshi E-commerce through fine-tuned large language models",
    journal: "Natural Language Processing Journal, Elsevier",
    year: 2025,
    url: "https://www.sciencedirect.com/science/article/pii/S2949719125000664",
    type: "journal" as const,
  },
  {
    title: "A smartphone-based multi-criteria vegetable object detection dataset from Bangladesh",
    journal: "Data in Brief, Elsevier",
    year: 2025,
    url: "https://www.sciencedirect.com/science/article/pii/S2352340925010029",
    type: "journal" as const,
  },
];

export const allPublications = {
  journals: [
    { title: "BDFlower: Growth stage flower image dataset for precision agriculture and floriculture", journal: "Data in Brief, Elsevier", year: 2026, url: "https://www.sciencedirect.com/science/article/pii/S2352340926002982" },
    { title: "Temperature-Optimized Self-Supervised Contrastive Learning Enables Data-Efficient and Explainable Fabric Defect Detection", journal: "IEEE Access, IEEE", year: 2026, url: "https://ieeexplore.ieee.org/abstract/document/11457882" },
    { title: "Real-Time Sunflower Detection Using Semi-Supervised and Self-Supervised Deep Learning for Precision Agriculture", journal: "Smart Agricultural Technology, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2772375525009153" },
    { title: "Attention guided convolutional neural network with explainable AI for papaya leaf disease detection in edge and drone agricultural systems", journal: "Scientific Reports, Nature Publishing Group", year: 2025, url: "https://www.nature.com/articles/s41598-025-25374-w" },
    { title: "A smartphone-based multi-criteria vegetable object detection dataset from Bangladesh", journal: "Data in Brief, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2352340925010029" },
    { title: "A comprehensive coin dataset highlighting the numismatic heritage of Bangladesh", journal: "Data in Brief, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2352340925009333" },
    { title: "BERT-KAN: Enhancing bilingual sentiment analysis in Bangladeshi E-commerce through fine-tuned large language models", journal: "Natural Language Processing Journal, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2949719125000664" },
    { title: "Real-Time Monitoring of Oyster Mushroom Cultivation Using CCTV and Attention-Enhanced ShuffleNet-Based Explainable AI Techniques", journal: "Smart Agricultural Technology, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2772375525008020" },
    { title: "Smartphone image dataset for turmeric plant leaf disease from Bangladesh spice fields", journal: "Data in Brief, Elsevier", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S2352340925009059" },
    { title: "Assessing the quality of DBpedia, LinkedGeoData, and Wikidata", journal: "Journal of Web Semantics, Elsevier", year: 2023, url: "https://doi.org/10.1016/j.websem.2023.100797" },
    { title: "Quality Assessment of Knowledge Graphs: A Systematic Literature Review", journal: "Semantic Web Journal, IOS Press", year: 2022, url: "#" },
    { title: "Anomaly Detection in Industrial IoT using Deep Neural Networks", journal: "IEEE Access, IEEE", year: 2021, url: "#" },
    { title: "Knowledge Base Population and Linked Data Quality Assessment", journal: "ACM Computing Surveys", year: 2020, url: "#" },
  ],
  conferences: [
    { title: "BCI-Based Motor Imagery Classification using Graph Attention Networks", journal: "IEEE ICCIT 2024", year: 2024, url: "#" },
    { title: "Precision Agriculture in Bangladesh: Challenges and Computer Vision Approaches", journal: "IEEE RAAICON 2024", year: 2024, url: "#" },
    { title: "Structured RAG with Property Graphs for Open-Domain Question Answering", journal: "ACM SAC 2024", year: 2024, url: "#" },
    { title: "Semi-Supervised Object Detection for Agricultural Applications in Low-Data Regimes", journal: "IEEE COMPAS 2023", year: 2023, url: "#" },
    { title: "IoT-Based Smart Agriculture Monitoring System with Edge AI", journal: "Springer ICDIIS 2022", year: 2022, url: "#" },
  ],
  bookChapters: [
    { title: "Knowledge Graph Quality Assessment: Dimensions, Metrics, and Methods", journal: "Chapman & Hall / CRC Press", year: 2023, url: "#" },
    { title: "Graph Neural Networks for Brain-Computer Interfaces", journal: "Chapman & Hall / CRC Press", year: 2024, url: "#" },
    { title: "Deep Learning for Precision Agriculture: A Practical Guide", journal: "IOS Press", year: 2024, url: "#" },
    { title: "Self-Supervised Learning in Computer Vision Applications", journal: "Chapman & Hall / CRC Press", year: 2023, url: "#" },
    { title: "IoT Security and Privacy: Blockchain Approaches", journal: "IOS Press", year: 2022, url: "#" },
    { title: "Retrieval-Augmented Generation Systems with Knowledge Graphs for Enterprise AI", journal: "Chapman & Hall / CRC Press", year: 2025, url: "#" },
  ],
};

export const researchAreas = [
  "Applied AI",
  "Computer Vision",
  "Knowledge Graphs",
  "Brain-Computer Interfaces",
  "Graph Neural Networks",
  "IoT & Smart Systems",
  "Blockchain Applications",
  "RAG & LLM Systems",
  "Sustainable AI",
  "Precision Agriculture AI",
];

export const tutorialSeries = [
  {
    slug: "ml-fundamentals",
    title: "Machine Learning Fundamentals",
    color: "teal" as CourseColor,
    icon: "🧠",
    level: "Beginner",
    episodeCount: 10,
    desc: "A ground-up introduction to machine learning — covering the math, algorithms, and Python implementations. For students who know basic programming but are new to ML.",
    topics: ["Linear Regression", "Decision Trees", "SVMs", "K-Means Clustering", "Neural Network Intro", "Model Evaluation", "Cross-Validation", "Feature Engineering", "Ensemble Methods", "Dimensionality Reduction"],
    comingSoon: true,
  },
  {
    slug: "deep-learning",
    title: "Deep Learning from Scratch",
    color: "purple" as CourseColor,
    icon: "🕸️",
    level: "Intermediate",
    episodeCount: 12,
    desc: "From backpropagation fundamentals through modern architectures. Each episode builds on the last, implementing key concepts in PyTorch with clear mathematical explanations.",
    topics: ["Backpropagation", "CNNs", "Batch Normalization", "Residual Networks", "Attention Mechanism", "Transformers", "Transfer Learning", "Training Tricks", "Regularization", "Model Deployment"],
    comingSoon: true,
  },
  {
    slug: "computer-vision",
    title: "Computer Vision Practicals",
    color: "amber" as CourseColor,
    icon: "👁️",
    level: "Intermediate",
    episodeCount: 10,
    desc: "Hands-on computer vision from classical feature detection through modern detection networks. Emphasizes practical implementation with real-world Bangladeshi datasets.",
    topics: ["Feature Detection", "Object Detection", "Image Segmentation", "Optical Flow", "Stereo Vision", "Self-supervised CV", "Model Deployment", "Edge AI", "NeRF Basics", "Vision Transformers"],
    comingSoon: true,
  },
];
